name : Test

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  log_message:
    runs-on: ubuntu-latest
    steps:
      - name: Log message
        run: echo "This is a test message from the GitHub Actions workflow working!."