name : Create as S3 Buckets

on:
  push:
    branches:
      - master
  workflow_dispatch: 

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  creating_bucket:
    runs-on: ubuntu-latest
    steps :
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          terraform plan \ 
            -var="bucket_name=${BUCKET_NAME}"
        working-directory: terraform

      - name: Terraform Apply
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform apply -auto-approve
        working-directory: terraform